# name: Scrape YouTube Data and Save to MongoDB
 
# on:
#   push:
#     branches:
#       - main  # Trigger the workflow when code is pushed to the main branch
#   workflow_dispatch:  # Allow the workflow to be triggered manually
#   schedule:
#     - cron: '0 */6 * * *'  # This triggers the workflow every hour on the hour



# jobs:
#   scrape:
#     runs-on: ubuntu-latest  # You can also use other environments such as windows-latest, if needed

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'  # Specify the Python version you want to use

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           # Install the required packages directly
#           pip install beautifulsoup4 selenium pymongo
        
#       - name: Run save-get-data-db.py script
#         env:
#           MONGO_URI: ${{ secrets.MONGO_URI }}
#         run: |
#           python ./scripts/save-get-data-db.py
